### PR TITLE
Add smrtlink bundle json

### PR DESCRIPTION
**Pull request by mpkocher**

### CODE REVIEW

**Comment by mpkocher** [comment]
Updated to the new bundle version spec. 

Please see for details:

https://github.com/PacificBiosciences/pbpipeline-helloworld-resources

**Comment by mpkocher** [comment]
See https://jira.pacificbiosciences.com/browse/DEP-59 for more context.

**Comment by mpkocher** [comment]
@jfalkner Can you review these changes?

**Comment by jfalkner** [comment]
Slow to catch, but seems fine. Capturing the needed ENV in the JSON. The links are helpful in noting this.

**Pull request merged**
